on:
  push:
    branches:
    - main

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: devops
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_INPUT: 0
      TF_LOG: INFO
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: login
      uses: azure/login@v2
      with:
        environment: azurecloud
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: terraform
      uses: hashicorp/setup-terraform@v3
    - name: terraform init
      run: terraform init -backend-config=storage_account_name=satfstateea -backend-config=container_name=tfstate -backend-config='key=${{ secrets.TERRAFORM_BACKEND_FILENAME }}'
